# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
# avoid duplicate tests in PRs
branches:
  only:
    - master
os:
  - linux
#  - osx
julia:
  - 1
#  - nightly
env:
  - GROUP=Interface
  - GROUP=Integrators_I
  - GROUP=Integrators_II
  - GROUP=Regression
  - GROUP=AlgConvergence_I
  - GROUP=AlgConvergence_II
  - GROUP=AlgConvergence_III
  - GROUP=Downstream
  - GROUP=ODEInterfaceRegression
addons:
  apt:
    packages:
      - gfortran
#matrix:
#  allow_failures:
#    - julia: nightly
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("OrdinaryDiffEq")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("OrdinaryDiffEq")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
